name = "connectgbb"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

pages_build_output_dir = ".open-next"
keep_names = false

[vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"

[env.production.vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"

[env.preview.vars]
SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://srrasrbsqajtssqlxoju.supabase.co"
NPM_FLAGS = "--legacy-peer-deps"
